#! /usr/bin/env python
# vim: set ai softtabstop=2 shiftwidth=2 tabstop=80 textwidth=180 :

if __name__ == '__main__':
  import poweroffd
  import sys

  app = poweroffd.Application()
  app.setup()
  try:
    app.run()
  except KeyboardInterrupt:
    sys.exit(0)
